Repository capstone45/backend, pull requests merged in 2022-02, with the labels that each got.

#14 config#9 : jest 환경 설정
  jest.config.ts
  package.json
  tests/index.spec.ts
Labels: Config

#10 feat#3: 검색 기능 구현
  package-lock.json
  src/index.ts
  src/recipe/recipe.controller.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
  src/tag/tag.controller.ts
  src/tag/tag.repository.ts
  src/tag/tag.service.ts
  src/user/user.controller.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: Feature

#19 docs : refactoring issue template 생성, typeorm 환경 설정
  .github/ISSUE_TEMPLATE/refactoring-issue.md
  .gitignore
  ormconfig.ts
  package-lock.json
  package.json
  src/index.ts
  tsconfig.json
  yarn.lock
Labels: Docs, Config

#22 Refactor#21 controller service to class
  src/user/dummy_data.ts
  src/user/user.controller.ts
  src/user/user.d.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: Refactor

#23 refactor#20 : Entry point (index.ts) 리펙토링 + Dependency Injection 적용
  src/index.ts
  src/user/index.ts
  tests/index.spec.ts
Labels: Refactor

#26 Fix#25 : Application, User controller, service, repository singleton 적용, DI 적용
  ormconfig.ts
  package.json
  src/index.ts
  src/user/index.ts
  src/user/user.controller.ts
  src/user/user.entity.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: Feature, Refactor, Fix

#28 refactor#27: 검색기능을 DB환경에 맞게 변경
  src/user/user.controller.ts
  src/user/user.d.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: Refactor

#30 feat, refactor#29 : controller, service, repository 추상 클래스 만들기
  .prettierrc.json
  src/user/dummy_data.ts
  src/user/index.ts
  src/user/user.controller.ts
  src/user/user.d.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: Feature, Refactor

#31 feat#24 : TypeORM Entity 구성
  src/entity/bookmark.entity.ts
  src/entity/date.entity.ts
  src/entity/recipeHasIngredient.entity.ts
  src/entity/recipeHasTag.entity.ts
  src/ingredient/ingredient.entity.ts
  src/recipe/recipe.entity.ts
  src/recipe/recipeDescription.entity.ts
  src/tag/tag.entity.ts
  src/user/subscribe.entity.ts
  src/user/user.entity.ts
Labels: Feature

#33 feat#32 : Recipe, tag Controller, Service, Repository 구성
  src/index.ts
  src/recipe/index.ts
  src/recipe/recipe.controller.ts
  src/recipe/recipe.d.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
  src/tag/index.ts
  src/tag/tag.controller.ts
  src/tag/tag.d.ts
  src/tag/tag.repository.ts
  src/tag/tag.service.ts
  src/user/user.repository.ts
Labels: Config

#34 Feat#4 : '최근 날짜 정렬' 검색, '오늘 생성된 레시피 중, 좋아요 많은 순 정렬' 검색 구현
  src/helper/helper.ts
  src/recipe/recipe.controller.ts
  src/recipe/recipe.d.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
  src/tag/tag.controller.ts
  src/user/user.controller.ts
Labels: Feature

#36 Feat#7 현재 접속한 유저가 구독한 쉐프들의 최신 레시피
  src/entity/date.entity.ts
  src/recipe/recipe.controller.ts
  src/recipe/recipe.d.ts
  src/recipe/recipe.entity.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
  src/tag/tag.controller.ts
  src/user/subscribe.entity.ts
  src/user/user.controller.ts
  src/user/user.entity.ts
Labels: Feature

#38 refactor : Entity 분리
  src/bookmark/bookmark.entity.ts
  src/date/date.entity.ts
  src/recipe-description/recipeDescription.entity.ts
  src/recipe-has-ingredient/recipeHasIngredient.entity.ts
  src/recipe-has-tag/recipeHasTag.entity.ts
  src/recipe/recipe.entity.ts
  src/subscribe/subscribe.entity.ts
  src/tag/tag.entity.ts
  src/user/user.entity.ts
Labels: Refactor

#40 refactor : Entity 연관관계 개선, PK 이름 변경
  src/bookmark/bookmark.entity.ts
  src/entity/date.entity.ts
  src/ingredient/ingredient.entity.ts
  src/recipe-description/description.ts
  src/recipe-has-ingredient/recipeHasIngredient.entity.ts
  src/recipe-has-tag/recipeHasTag.entity.ts
  src/recipe-ingredient/recipe-ingredient.ts
  src/recipe-tag/recipe-tag.entity.ts
  src/recipe/recipe.entity.ts
  src/subscribe/subscribe.entity.ts
  src/tag/tag.entity.ts
  src/user/user.entity.ts
Labels: Refactor, Fix
