Repository capstone45/backend, pull requests merged in 2022-03, with the labels that each got.

#41 Refactor : entity 연관관계 개선, entity 분리
  src/bookmark/bookmark.entity.ts
  src/recipe-description/recipe-description.entity.ts
  src/recipe-ingredient/recipe-ingredient.entity.ts
  src/recipe-tag/recipe-tag.entity.ts
  src/recipe/recipe.entity.ts
  src/subscribe/subscribe.entity.ts
  src/tag/tag.entity.ts
  src/user/user.entity.ts
Labels: Refactor

#47 feat#5 : PK로 recipe 찾기 구현
  src/recipe/recipe.controller.ts
  src/recipe/recipe.d.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
Labels: Feature

#49 feat#48 : 유저 정보 업데이트 구현
  src/user/user.controller.ts
  src/user/user.d.ts
  src/user/user.entity.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: Feature

#52 Feat#51 user thumbnail url update
  src/user/user.controller.ts
  src/user/user.d.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: Feature

#57 Refactor#56 di container
  .gitignore
  src/container.ts
  src/index.ts
  src/recipe-description/recipe-description.entity.ts
  src/recipe/index.ts
  src/recipe/recipe.controller.ts
  src/recipe/recipe.d.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
  src/tag/index.ts
  src/tag/tag.controller.ts
  src/tag/tag.d.ts
  src/tag/tag.repository.ts
  src/tag/tag.service.ts
  src/user/index.ts
  src/user/user.controller.ts
  src/user/user.d.ts
  src/user/user.repository.ts
  src/user/user.service.ts
  tests/index.spec.ts
Labels: Refactor

#58 refactor : Date info Entity 리펙토링
  src/container.ts
  src/entity/dateInfo.entity.ts
  src/index.ts
  src/recipe/recipe.entity.ts
  src/user/user.entity.ts
Labels: Refactor

#60 Fix#59 router 등록
  src/container.ts
  src/index.ts
Labels: Fix, Solved

#62 Refactor#61 detach domain
  src/recipe-description/recipe-description.entity.ts
  src/recipe/recipe.controller.ts
  src/recipe/recipe.d.ts
  src/recipe/recipe.entity.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
  src/recipe/type/recipeController.d.ts
  src/recipe/type/recipeRepository.d.ts
  src/recipe/type/recipeService.d.ts
  src/tag/tag.controller.ts
  src/tag/tag.d.ts
  src/tag/tag.repository.ts
  src/tag/tag.service.ts
  src/tag/type/data.d.ts
  src/tag/type/tagController.d.ts
  src/tag/type/tagRepository.d.ts
  src/tag/type/tagService.d.ts
  src/user/type/data.d.ts
  src/user/type/userController.d.ts
  src/user/type/userRepository.d.ts
  src/user/type/userService.d.ts
  src/user/user.controller.ts
  src/user/user.d.ts
  src/user/user.entity.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: Refactor

#64 Refactor#63 create recipe
  src/bookmark/bookmark.entity.ts
  src/container.ts
  src/ingredient/ingredient.entity.ts
  src/ingredient/type/ingredient.repository.ts
  src/ingredient/type/ingredientRepository.d.ts
  src/recipe-ingredient/recipe-ingredient.entity.ts
  src/recipe-tag/recipe-tag.entity.ts
  src/recipe/recipe.controller.ts
  src/recipe/recipe.entity.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
  src/recipe/type/data.d.ts
  src/recipe/type/recipeRepository.d.ts
  src/recipe/type/recipeService.d.ts
  src/recipeDescription/recipeDescription.entity.ts
  src/recipeIngredient/recipeIngredient.entity.ts
  src/recipeIngredient/recipeIngredient.repository.ts
  src/recipeIngredient/type/recipeIngredientRepository.d.ts
  src/recipeTag/recipeTag.entity.ts
  src/recipeTag/recipeTag.repository.ts
  src/recipeTag/type/recipeTagRepository.d.ts
  src/tag/tag.entity.ts
  src/tag/tag.repository.ts
  src/tag/tag.service.ts
  src/tag/type/data.d.ts
  src/tag/type/tagRepository.d.ts
  src/tag/type/tagService.d.ts
  src/user/type/data.d.ts
  src/user/type/userController.d.ts
  src/user/type/userRepository.d.ts
  src/user/type/userService.d.ts
Labels: Refactor, Fix

#76 Feat#54 : update recipe 구현
  .gitignore
  src/container.ts
  src/recipe/recipe.service.ts
  src/recipeDescription/recipeDescription.entity.ts
  src/recipeDescription/recipeDescription.repository.ts
  src/recipeDescription/type/recipeDescriptionRepository.d.ts
  src/recipeIngredient/recipeIngredient.repository.ts
  src/recipeIngredient/type/recipeIngredientRepository.d.ts
  src/recipeTag/recipeTag.repository.ts
  src/recipeTag/type/recipeTagRepository.d.ts
  src/user/type/userRepository.d.ts
Labels: Feature

#82 Feat#81 bookmark 구현
  src/bookmark/bookmark.controller.ts
  src/bookmark/bookmark.entity.ts
  src/bookmark/bookmark.repository.ts
  src/bookmark/bookmark.service.ts
  src/bookmark/type/bookmarkController.d.ts
  src/bookmark/type/bookmarkRepository.d.ts
  src/bookmark/type/bookmarkService.d.ts
  src/container.ts
  src/recipe/recipe.entity.ts
  src/recipe/recipe.service.ts
  src/user/user.entity.ts
  src/user/user.service.ts
Labels: Feature

#84 Fix#73 find today most liked
  ormconfig.ts
  src/bookmark/repository.ts
  src/bookmark/service.ts
  src/bookmark/type/repository.d.ts
  src/container.ts
  src/helper/helper.ts
  src/recipe/entity.ts
  src/recipe/repository.ts
  src/recipe/service.ts
  src/recipe/type/service.d.ts
Labels: Fix

#87 Refactor#86 exception
  src/bookmark/controller.ts
  src/bookmark/service.ts
  src/helper/helper.ts
  src/recipe/controller.ts
  src/recipe/service.ts
  src/recipe/type/error.ts
  src/recipe/type/service.d.ts
  src/subscribe/controller.ts
  src/subscribe/service.ts
  src/subscribe/type/service.d.ts
  src/tag/controller.ts
  src/tag/repository.ts
  src/tag/service.ts
  src/tag/type/service.d.ts
  src/user/controller.ts
  src/user/service.ts
  src/user/type/error.ts
  src/user/type/service.d.ts
Labels: Refactor

#91 config#90 실행환경 분리
  ormconfig.ts
  package.json
  src/container.ts
  src/index.ts
  yarn.lock
Labels: Config

#96 Fix#94 bcrypt =>using updated develop branch
  .gitignore
  README.md
  package.json
  yarn.lock
Labels: Docs, Fix

#97 Fix#testing btcrypt environment
  src/user/entity.ts
  src/user/service.ts
  src/user/type/dto.ts
  src/user/type/service.d.ts
Labels: Feature, Fix

#98 Feat#13 authorization middleware
  package.json
  src/index.ts
  src/user/controller.ts
  src/user/entity.ts
  src/user/service.ts
  src/user/type/controller.d.ts
  src/user/type/dto.ts
  src/user/type/service.d.ts
  yarn.lock
Labels: Bug, Hot Fix, Fix, Config

#101 Feat#99 today chef
  src/recipe/repository.ts
  src/recipe/service.ts
  src/recipe/type/repository.d.ts
  src/user/controller.ts
  src/user/repository.ts
  src/user/service.ts
  src/user/type/controller.d.ts
  src/user/type/repository.d.ts
  src/user/type/service.d.ts
Labels: Feature

#102 Feat#100 user recommend recipe
  src/container.ts
  src/recipe/controller.ts
  src/recipe/repository.ts
  src/recipe/service.ts
  src/recipe/type/controller.d.ts
  src/recipe/type/repository.d.ts
  src/recipe/type/service.d.ts
  src/userIngredient/entity.ts
  src/userIngredient/repository.ts
  src/userIngredient/type/repository.d.ts
Labels: Feature

#107 Refactor#106auth modify
  src/user/controller.ts
  src/user/service.ts
  src/user/type/controller.d.ts
  src/user/type/service.d.ts
Labels: Feature, Hot Fix, Refactor, Fix, Config, Solved
